# Generated by Django 4.2.3 on 2023-08-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tele_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('post_header', models.CharField(max_length=80)),
                ('post_content', models.CharField(max_length=240)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='tele',
        ),
    ]
