# Generated by Django 4.2.3 on 2023-08-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele', '0002_tele_class_delete_tele'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tele_class',
            name='post_date',
            field=models.DateTimeField(verbose_name='08-15-2023'),
        ),
    ]
